### ISSUE TITLE
[INIT] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by taeheeL** [boostcampwm-2024/and05-MAPISODE#1]
## 🚩 TODO
**[Github]** 
- [x] Wiki
- [x] PR
- [x] Branch
- [x] Project
- [x] Milestone
- [x] label
- [x] gitignore 설정
- [x] CI (Github Action)
- [x] WEB-HOOK 디스코드 연동

**[Android]**
- [x] build-logic 구성
- [x] 멀티 모듈 기초 설계
- [ ] Util 클래스 세팅
- [ ] mock 데이터로 틀 구성

## ⏲️ Time Plan
    - 10 시간
