### ISSUE TITLE
[FEAT] 에피소드 생성 / 이미지 첨부 기능

### ISSUE THREAD

**Issue by Ameri-Kano** [boostcampwm-2024/and05-MAPISODE#100]
## 🚩 TODO
- [ ] coil 라이브러리 의존성 추가
- [ ] 에피소드 생성 화면에서 이미지 출력
- [ ] 이미지 클라우드에 업로드

## ⏲️ Time Plan
    - 3 시간
