### ISSUE TITLE
[FEAT] Group / 화면 구성 2차

### ISSUE THREAD

**Issue by TaewoongR** [boostcampwm-2024/and05-MAPISODE#101]
## 🚩 TODO
- [x] 그룹 참여 서버연결
- [ ] 그룹 생성 화면 제작 및 서버 연결
- [ ] 그룹 상세 화면 제작 및 서버 연결

## ⏲️ Time Plan
    - 10 시간
