### ISSUE TITLE
[FEAT] Home / 에피소드 상세

### ISSUE THREAD

**Issue by haeti-dev** [boostcampwm-2024/and05-MAPISODE#125]
## 🚩 TODO
- [x] 에피소드 카드 디자인 수정
- [x] 카드에서 id 받아서 에피소드 상세 화면으로 전달
- [x] 에피소드 상세 화면 구현 

## ⏲️ Time Plan
    - 3 시간
