### ISSUE TITLE
[FEAT] Auth / 그룹 관련 작업

### ISSUE THREAD

**Issue by shinythinking** [boostcampwm-2024/and05-MAPISODE#145]
## 🚩 TODO
- [ ] 회원가입시, uid로 그룹 만들기
- [ ] datastore에 RecentSelectedGroup 저장
- [ ] user에 그룹 추가( 나의 에피소드를 0번 인덱스로! )

## ⏲️ Time Plan
    - 1.5 시간
