### ISSUE TITLE
[FEAT] DB 통신 인터페이스 구현

### ISSUE THREAD

**Issue by Ameri-Kano** [boostcampwm-2024/and05-MAPISODE#15]
## 🚩 TODO
- [x] Firestore 데이터베이스 연동
- [ ] DB에 저장할 데이터 스키마 정의 및 코틀린 데이터 클래스 작성
- [ ] 각 데이터 클래스의 DB 읽기/쓰기 인터페이스 구현

## ⏲️ Time Plan
    - 9 시간
