### ISSUE TITLE
[CHORE] Designsystem / Theme Color 수정

### ISSUE THREAD

**Issue by TaewoongR** [boostcampwm-2024/and05-MAPISODE#23]
## 🚩 TODO
- [ ] Color Scheme 속성 수정
- [ ] 수정된 속성에 따른 컴포넌트 색상 변경
- [ ] WindowInsects 컬러 수정

## ⏲️ Time Plan
    - 5 시간
