### ISSUE TITLE
[INIT] Designsystem / svg 추가

### ISSUE THREAD

**Issue by TaewoongR** [boostcampwm-2024/and05-MAPISODE#37]
## 🚩 TODO
- [x] 마커로 사용될 svg 추가
- [x] Top App Bar에 사용될 아이콘 svg 추가
- [x] 다른 모듈의 resource에 존재하는 svg 한곳에서 관리

## ⏲️ Time Plan
    - 1 시간
