### ISSUE TITLE
[FEAT] Home / Custom BottomSheet 구현 및 연동

### ISSUE THREAD

**Issue by haeti-dev** [boostcampwm-2024/and05-MAPISODE#66]
## 🚩 TODO
- [ ] core:designsystem에 커스텀 버텀시트 구현
- [ ] Home에 MVI 패턴으로 바텀시트 컨트롤
- [ ] 바텀 시트 content 구현 

## ⏲️ Time Plan
    - 4 시간
