### ISSUE TITLE
[FEAT] 에피소드 생성 화면 / 에피소드 생성 기능 최소 구현

### ISSUE THREAD

**Issue by Ameri-Kano** [boostcampwm-2024/and05-MAPISODE#71]
## 🚩 TODO
- [ ] 현재 지도의 중앙 위치를 바탕으로 에피소드 위치 가져오기
- [ ] 입력값을 State로 관리
- [ ] State를 바탕으로 Episode 등록 구현

## ⏲️ Time Plan
    - 9 시간
