### ISSUE TITLE
[FIX] Oauth / Google Oauth API 레벨 대응

### ISSUE THREAD

**Issue by TaewoongR** [boostcampwm-2024/and05-MAPISODE#84]
## 🚩 TODO
- [x] 구글 Oauth 로직에서 쓰이는 context 를 ApplicationContext가 아닌 ActivityContext로 변환
  - API 30, 33 기기에서 ApplicationContext 를 사용할 때 실행이 안되는 문제 발견
- [x] domain:auth - data:auth 모듈에서 core:auth 로 이전
- [x] hilt 를 통해 ApplicationContext를 core:auth 에 주입하는 대신 feature:auth 에서 직접 함수호출하여 인자로 ActivityContext를 전달
  - core:auth 에서는 생명주기를 알 수 없으므로 ActivityContext를 주입할 수 없음

- open https://github.com/boostcampwm-2024/and05-MAPISODE/pull/80#discussion_r1851171779

https://github.com/user-attachments/assets/4362646f-6e7d-474e-b32e-d5c7ffee8196

https://github.com/user-attachments/assets/5081a6d2-751a-49dc-a6b2-e6c67d1b5cc1

## ⏲️ Time Plan
    - 3 시간
