### ISSUE TITLE
[FEAT] Group /  네비게이션 설정

### ISSUE THREAD

**Issue by TaewoongR** [boostcampwm-2024/and05-MAPISODE#86]
## 🚩 TODO
- [x] NavGraph, NavHost 선언
- [x] Type-safe 적용
- [x] BotAppBar 숨기는 CompositionalLocal 활용 로직 삭제

## ⏲️ Time Plan
    - 2 시간
