### ISSUE TITLE
[FEAT] SignIn / 로직 구현

### ISSUE THREAD

**Issue by shinythinking** [boostcampwm-2024/and05-MAPISODE#91]
## 🚩 TODO
- [ ] datastore에 유저 저장하는 메서드 만들기
- [ ] user에 대한 데이터 클래스 구성하기
- [ ] mvi 패턴 활용해서 로직 구성
- [ ] 

## ⏲️ Time Plan
    - 6 시간
