### ISSUE TITLE
[FEAT] Group / UI 구성 1차

### ISSUE THREAD

**Issue by TaewoongR** [boostcampwm-2024/and05-MAPISODE#95]
## 🚩 TODO
- [x] 그룹 참여 화면
- [x] 그룹 생성 화면
- [x] FireStore 와 뷰모델 연결 (data - domain - viewmodel)

## ⏲️ Time Plan
    - 6 시간
